ingress-nginx:
  controller:
    enabled: true
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
        service.beta.kubernetes.io/disable-ssl: "true"
    ingressClass: nginx
    ingressClassResource:
      name: nginx

ingress:
  name: application-ingress
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"


frontend:
  name: frontend
  appLabel: frontend
  replicaCount: 2
  containerPort: 80
  image:
    repository: 058264138725.dkr.ecr.us-east-1.amazonaws.com/pandak8s-web
    tag: 0.0.1
    pullPolicy: Always
  env:
    backendHost: backend
  service:
    port: 80
    type: ClusterIP

backend:
  name: backend
  appLabel: backend
  replicaCount: 3
  containerPort: 8080
  image:
    repository: 058264138725.dkr.ecr.us-east-1.amazonaws.com/pandak8s-api
    tag: 0.0.1
    pullPolicy: Always
  service:
    port: 80
    type: ClusterIP
  serviceAccountName: backend-sa
  rbac:
    enabled: true
    fullAccessRole:
      name: backend-full-access
    fullAccessBinding:
      name: backend-clusterrole-binding
    readonlyRole:
      name: backend-readonly
      namespace: kube-system
    readonlyBinding:
      name: backend-readonly-binding