version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - FLASK_ENV=development
      - KUBECONFIG=.kube/config
    volumes:
      - $HOME/.kube:/root/.kube:ro
    networks:
      - compose-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "http://backend:8080"
    container_name: frontend
    ports:
      - "8080:80"
    networks:
      - compose-network

networks:
  compose-network:
    driver: bridge
