apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pandak8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TomBrov/NameSpceExplorer
    targetRevision: HEAD
    path: pandak8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true