apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.backend.rbac.fullAccessBinding.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.backend.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.backend.rbac.fullAccessRole.name }}
  apiGroup: rbac.authorization.k8s.io
