apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.backend.rbac.readonlyRole.name }}
  namespace: {{ .Values.backend.rbac.readonlyRole.namespace }}
rules:
  {{ toYaml .Values.backend.rbac.readonlyRole.rules | indent 2 }}
