name: docker-build-push
description: Builds and pushes a Docker image to ECR using make targets

inputs:
  registry:
    description: ECR registry URL
    required: true

  product_name:
    description: Product name
    required: true

  service:
    description: Service name
    required: true

  tag:
    description: Docker tag
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker Image (make build-ci)
      working-directory: app/${{ inputs.service }}
      shell: bash
      run: |
        make build-ci \
          REGISTRY=${{ inputs.registry }} \
          PRODUCT=${{ inputs.product_name }} \
          SERVICE=${{ inputs.service }} \
          TAG=${{ inputs.tag }}

    - name: Push Docker Image (make push-ci)
      working-directory: app/${{ inputs.service }}
      shell: bash
      run: |
        make push-ci \
          REGISTRY=${{ inputs.registry }} \
          PRODUCT=${{ inputs.product_name }} \
          SERVICE=${{ inputs.service }} \
          TAG=${{ inputs.tag }}
