name: PandaK8s CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.get-changes.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed services
        id: get-changes
        run: |
          echo "Checking for changes in app/frontend and app/backend directories"
          changed_services=()
          
          if git diff --name-only HEAD^ HEAD | grep -q 'app/frontend'; then
            changed_services+=("frontend")
          fi
          
          if git diff --name-only HEAD^ HEAD | grep -q 'app/backend'; then
            changed_services+=("backend")
          fi
          
          json=$(printf '%s\n' "${changed_services[@]}" | jq -R . | jq -s .)
          echo "Changed services: $json"
          echo "service=$json" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: get-changes
    if: needs.get-changes.outputs.services != '[""]'
    strategy:
      matrix:
        service: ${{ fromJson(needs.get-changes.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: ./.github/actions/docker-build-push
        with:
          tag: latest
          service: ${{ matrix.service }}