name: PandaK8s CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      service: ${{ steps.set-service.outputs.service }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed services
        id: get-changes
        run: |
          echo "Checking for changes in app/frontend and app/backend directories"
          if git diff --name-only HEAD^ HEAD | grep -q 'app/frontend'; then
            echo "frontend" >> changed_services.txt
          fi
          if git diff --name-only HEAD^ HEAD | grep -q 'app/backend'; then
            echo "backend" >> changed_services.txt
          fi
          echo "Changed services: $(cat changed_services.txt)"
          echo "::set-output name=service::$(cat changed_services.txt)"

  build-and-push:
    runs-on: ubuntu-latest
    needs: get-changes
    strategy:
      matrix:
        service: ${{ fromJson(needs.get-changes.outputs.service) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: ./.github/actions/docker-build-push
        with:
          tag: latest
          service: ${{ matrix.service }}