name: PandaK8s CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.matrix.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'app/web/**'
            backend:
              - 'app/api/**'

      - name: Generate matrix
        id: matrix
        run: |
          changed=()
          
          if [[ "${{ steps.filter.outputs.frontend }}" == 'true' ]]; then
            echo "Frontend has changed"
            changed+=("\"web\"")
          fi
          
          if [[ "${{ steps.filter.outputs.backend }}" == 'true' ]]; then
            echo "Backend has changed"
            changed+=("\"api\"")
          fi
          
          json="[$(IFS=,; echo "${changed[*]}")]"
          echo "services=$json" >> $GITHUB_OUTPUT

  build-and-push:
    runs-on: ubuntu-latest
    needs: get-changes
    if: needs.get-changes.outputs.services != '[]'
    strategy:
      matrix:
        service: ${{ fromJson(needs.get-changes.outputs.services) }}

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Docker Image
        uses: ./.github/actions/docker-build-push
        with:
          registry: ${{ steps.login-ecr.outputs.registry }}
          product_name: pandak8s
          service: ${{ matrix.service }}
          tag: latest
